/**
 * Script to generate a static list of all Fluent UI icon names
 * by parsing the TypeScript declaration files.
 * 
 * Run: npx tsx scripts/generate-icon-list.ts
 */

import fs from "node:fs";
import path from "node:path";

const ICONS_DIR = path.join(process.cwd(), "node_modules/@fluentui/react-icons/lib/icons");
const OUTPUT_FILE = path.join(process.cwd(), "src/icon-names.ts");

function extractIconNamesFromDts(filePath: string): string[] {
  const content = fs.readFileSync(filePath, "utf-8");
  const iconNames: string[] = [];
  
  // Match: export declare const IconName: FluentIcon;
  const regex = /export declare const (\w+): FluentIcon;/g;
  let match;
  
  while ((match = regex.exec(content)) !== null) {
    iconNames.push(match[1]);
  }
  
  return iconNames;
}

function getAllDtsFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  
  return fs.readdirSync(dir)
    .filter(file => file.endsWith(".d.ts"))
    .map(file => path.join(dir, file));
}

function main() {
  console.log("Extracting Fluent UI icon names...");
  
  const allIconNames: Set<string> = new Set();
  
  // Process icons directory only (unsized bundled icons)
  const iconFiles = getAllDtsFiles(ICONS_DIR);
  for (const file of iconFiles) {
    const names = extractIconNamesFromDts(file);
    names.forEach(name => allIconNames.add(name));
  }
  
  const iconNamesArray = Array.from(allIconNames).sort();
  
  console.log(`Found ${iconNamesArray.length} icons`);
  
  // Generate TypeScript file
  const output = `// Auto-generated list of Fluent UI icon names
// Generated by: npx tsx scripts/generate-icon-list.ts
// Total icons: ${iconNamesArray.length}

export const FLUENT_ICON_NAMES: readonly string[] = [
${iconNamesArray.map(name => `  "${name}",`).join("\n")}
] as const;

export type FluentIconName = typeof FLUENT_ICON_NAMES[number];
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`Generated: ${OUTPUT_FILE}`);
}

main();
