/**
 * Script to generate an icon registry that maps icon names to their components
 * for use in the client-side icon preview.
 * 
 * Run: npx tsx scripts/generate-icon-registry.ts
 */

import fs from "node:fs";
import path from "node:path";

const ICONS_DIR = path.join(process.cwd(), "node_modules/@fluentui/react-icons/lib/icons");
const OUTPUT_FILE = path.join(process.cwd(), "src/icon-registry.tsx");

function extractIconNamesFromDts(filePath: string): string[] {
  const content = fs.readFileSync(filePath, "utf-8");
  const iconNames: string[] = [];
  
  // Match: export declare const IconName: FluentIcon;
  const regex = /export declare const (\w+): FluentIcon;/g;
  let match;
  
  while ((match = regex.exec(content)) !== null) {
    iconNames.push(match[1]);
  }
  
  return iconNames;
}

function getAllDtsFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  
  return fs.readdirSync(dir)
    .filter(file => file.endsWith(".d.ts"))
    .map(file => path.join(dir, file));
}

function main() {
  console.log("Generating icon registry...");
  
  const allIconNames: Set<string> = new Set();
  
  // Process icons directory only (not sizedIcons)
  const iconFiles = getAllDtsFiles(ICONS_DIR);
  for (const file of iconFiles) {
    const names = extractIconNamesFromDts(file);
    names.forEach(name => allIconNames.add(name));
  }
  
  // Use all icons from the icons folder (these are unsized bundled icons)
  const filteredIcons = Array.from(allIconNames)
    .filter(name => name.match(/(Regular|Filled|Color)$/))
    .sort();
  
  console.log(`Found ${allIconNames.size} total icons, filtered to ${filteredIcons.length} for registry`);
  
  // Generate TypeScript file with explicit imports
  const imports = filteredIcons.map(name => `  ${name}`).join(",\n");
  
  const registryEntries = filteredIcons.map(name => `  "${name}": ${name}`).join(",\n");
  
  const output = `// Auto-generated icon registry
// Generated by: npx tsx scripts/generate-icon-registry.ts
// Total icons: ${filteredIcons.length}

import type { FluentIconsProps } from "@fluentui/react-icons";
import {
${imports}
} from "@fluentui/react-icons";

export type IconComponent = React.ComponentType<FluentIconsProps>;

export const ICON_REGISTRY: Record<string, IconComponent> = {
${registryEntries}
};

export function getIconComponent(name: string): IconComponent | null {
  return ICON_REGISTRY[name] || null;
}
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`Generated: ${OUTPUT_FILE}`);
}

main();
