/**
 * Script to generate a mapping of icon names to their available sizes.
 * This reads from the sizedIcons folder to find all available sizes.
 * 
 * Run: npx tsx scripts/generate-icon-sizes.ts
 */

import fs from "node:fs";
import path from "node:path";

const SIZED_ICONS_DIR = path.join(process.cwd(), "node_modules/@fluentui/react-icons/lib/sizedIcons");
const OUTPUT_FILE = path.join(process.cwd(), "src/icon-sizes.ts");

function extractIconNamesFromDts(filePath: string): string[] {
  const content = fs.readFileSync(filePath, "utf-8");
  const iconNames: string[] = [];
  
  // Match: export declare const IconName: FluentIcon;
  const regex = /export declare const (\w+): FluentIcon;/g;
  let match;
  
  while ((match = regex.exec(content)) !== null) {
    iconNames.push(match[1]);
  }
  
  return iconNames;
}

function getAllDtsFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  
  return fs.readdirSync(dir)
    .filter(file => file.endsWith(".d.ts"))
    .map(file => path.join(dir, file));
}

function parseIconName(name: string): { baseName: string; size: string; variant: string } | null {
  // Pattern: BaseName + Size (number) + Variant (Regular/Filled/Color)
  const match = name.match(/^(.+?)(\d+)(Regular|Filled|Color)$/);
  if (match) {
    return {
      baseName: match[1],
      size: match[2],
      variant: match[3],
    };
  }
  return null;
}

function main() {
  console.log("Generating icon sizes mapping...");
  
  const allSizedIcons: string[] = [];
  
  // Process sizedIcons directory
  const sizedIconFiles = getAllDtsFiles(SIZED_ICONS_DIR);
  for (const file of sizedIconFiles) {
    const names = extractIconNamesFromDts(file);
    allSizedIcons.push(...names);
  }
  
  console.log(`Found ${allSizedIcons.length} sized icons`);
  
  // Build a map: "BaseNameVariant" -> [sizes]
  const sizesMap: Record<string, string[]> = {};
  
  for (const name of allSizedIcons) {
    const parsed = parseIconName(name);
    if (parsed) {
      const key = `${parsed.baseName}${parsed.variant}`;
      if (!sizesMap[key]) {
        sizesMap[key] = [];
      }
      if (!sizesMap[key].includes(parsed.size)) {
        sizesMap[key].push(parsed.size);
      }
    }
  }
  
  // Sort sizes numerically for each icon
  for (const key of Object.keys(sizesMap)) {
    sizesMap[key].sort((a, b) => parseInt(a) - parseInt(b));
  }
  
  console.log(`Generated sizes for ${Object.keys(sizesMap).length} base icons`);
  
  // Generate TypeScript file
  const entries = Object.entries(sizesMap)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, sizes]) => `  "${key}": [${sizes.map(s => `"${s}"`).join(", ")}]`)
    .join(",\n");
  
  const output = `// Auto-generated icon sizes mapping
// Generated by: npx tsx scripts/generate-icon-sizes.ts
// Maps base icon names (e.g., "SendRegular") to available sizes

export const ICON_SIZES: Record<string, string[]> = {
${entries}
};

export function getIconSizes(baseName: string): string[] {
  return ICON_SIZES[baseName] || [];
}
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`Generated: ${OUTPUT_FILE}`);
}

main();
